apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-container
          image: worker:latest
          resources:
            limits:
              memory: '64Mi'
              cpu: '250m'
          imagePullPolicy: IfNotPresent
